#!/bin/bash

set -e

# Reset controller token
# pwgen -1 > /etc/cozy/controller.token
# chown cozy-home /etc/cozy/controller.token
# chmod 700 /etc/cozy/controller.token
# supervisorctl restart cozy-controller

# Restart cozy-controller when CouchDB is available
while ! curl -s 127.0.0.1:5984; do sleep 5; done
cozy-monitor restart-cozy-stack
